# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: bf7a16254ec96b084a6caf3d435ec18f0f245cc7 # 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 50c5478ed9e10bf360335449280cf2a67f4edb7a # v2.7.1
    hooks:
      - id: prettier
        files: \.(css|html|md|yml|yaml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/asottile/pyupgrade
    rev: aa5af9cd273894d0246e0eb9fa5ad557037481dc # v3.7.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
