[build.environment]
  HUGO_VERSION = "0.91.2"

[[redirects]]
  from = "/scipylib"
  to = "/"

[[redirects]]
  from = "/scipylib/license.html"
  to = "https://github.com/scipy/scipy/blob/main/LICENSE.txt"

[[redirects]]
  from = "/scipylib/download.html"
  to = "/download/"

[[redirects]]
  from = "/scipylib/mailing-lists.html"
  to = "/mailing-lists/"

[[redirects]]
  from = "/scipylib/bug-report.html"
  to = "/bug-report/"

[[redirects]]
  from = "/scipylib/dev-zone.html"
  to = "/dev-zone/"

[[redirects]]
  from = "/scipylib/donations.html"
  to = "/donations/"

[[redirects]]
  from = "/scipylib/faq.html"
  to = "/faq/"
